apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
  labels:
    app: flask-backend
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: indura08/flask-react-application:flask-backend
          ports:
            - containerPort: 5000